{
  lib,
  fetchurl,
  fetchFromGitHub,
  cmake,
  unzip,
  makeWrapper,
  boost188,
  llvmPackages_22,
  gmp,
  emacs,
  jre_headless,
  tcl,
  tk,
}:

let
  llvmPackages = llvmPackages_22;
  stdenv = llvmPackages.stdenv;
  pname = "mozart2";
  version = "2.0.1-unstable-2026-08-09";

  # This is a workaround to avoid using sbt.
  # I guess it is acceptable to fetch the bootstrapping compiler in binary form.
  bootcompiler = fetchurl {
    url = "https://github.com/layus/mozart2/releases/download/v2.0.0-beta.1/bootcompiler.jar";
    sha256 = "1hgh1a8hgzgr6781as4c4rc52m2wbazdlw3646s57c719g5xphjz";
  };

  # The mozart2 fork's .gitmodules still points stdlib at the old upstream
  # mozart/mozart2-stdlib, but the same author forked and modernized the stdlib
  # too (CMake 4, add_subdirectory_and_log). fetchSubmodules pulls the stale one,
  # so fetch the updated fork and swap it in below.
  stdlib = fetchFromGitHub {
    owner = "matdubuisson";
    repo = "mozart2-stdlib";
    rev = "28e61a0b398ff9fb1b34666d3687ba379295f74c";
    hash = "sha256-VIketHEGXaLuxvS09giIiVt4CNd2EPLOHiCoPhDG/FI=";
  };
in
stdenv.mkDerivation {
  inherit pname version;

  # The matdubuisson fork modernizes the build to GCC 15 / Clang 22, Boost 1.88,
  # CMake 4 and C++20. There is no release tarball, so we build from a checkout
  # with the stdlib and gtest submodules.
  src = fetchFromGitHub {
    owner = "matdubuisson";
    repo = "mozart2";
    rev = "35e0f79ada21d00ef267569e44a0e409ce7741fd";
    hash = "sha256-RPOfmZtvqxgRhuE21hrympBQAcPhnm0NoC6Tl7aMLbQ=";
    fetchSubmodules = true;
  };

  # Replace the stale stdlib submodule (pinned to old upstream via .gitmodules)
  # with the author's modernized fork, which the rest of the fork expects.
  postPatch = ''
    rm -rf stdlib
    cp -r --no-preserve=mode,ownership ${stdlib} stdlib
  '';

  postConfigure = ''
    cp ${bootcompiler} bootcompiler/bootcompiler.jar
  '';

  # With MOZART_CACHED_BUILD=OFF the VM sources are generated by a clang-based
  # generator. The upstream README builds these explicitly before the rest, so
  # do the same to keep the ordering deterministic.
  preBuild = ''
    make -B gensources genboostsources VERBOSE=1 -j$NIX_BUILD_CORES
  '';

  nativeBuildInputs = [
    cmake
    makeWrapper
    unzip
  ];

  cmakeFlags = [
    "-DBoost_USE_STATIC_LIBS=OFF"
    "-DMOZART_BOOST_USE_STATIC_LIBS=OFF"
    # Regenerate the VM sources from scratch instead of using cached ones; this
    # is what drives the clang-based generator against the current toolchain.
    "-DMOZART_CACHED_BUILD=OFF"
    "-DClang_DIR=${llvmPackages.clang-unwrapped.dev}/lib/cmake/clang"
    "-DLLVM_DIR=${llvmPackages.llvm.dev}/lib/cmake/llvm"
    # We are building with clang, as nix does not support having clang and
    # gcc together as compilers and we need clang for the sources generation.
    # However, clang emits tons of warnings about gcc's atomic-base library.
    "-DCMAKE_CXX_FLAGS=-Wno-braced-scalar-init"
  ];

  fixupPhase = ''
    wrapProgram $out/bin/oz --set OZEMACS ${emacs}/bin/emacs
  '';

  buildInputs = [
    boost188
    gmp
    emacs
    jre_headless
    tcl
    tk
    # The VM source generator is a clang tool and needs clang's own development
    # headers (clang/Frontend/ASTUnit.h, ...); upstream's CMake only adds LLVM's
    # include dir, so make clang's headers available through the compiler wrapper.
    llvmPackages.clang-unwrapped.dev
  ];

  meta = {
    description = "Open source implementation of Oz 3";
    maintainers = with lib.maintainers; [
      layus
      h7x4
    ];
    license = lib.licenses.bsd2;
    homepage = "https://mozart.github.io";
    platforms = lib.platforms.all;
    # Trace/BPT trap: 5
    broken = stdenv.hostPlatform.isDarwin;
  };

}
